"""ProbLog refactoring strategy — Stream 6 / Leaf H.

Single-LSP strategy: ``swipl`` + ``lsp_server`` pack, shared with Prolog.
ProbLog (https://problog.readthedocs.io/) is a **research-mode** probabilistic
logic programming language — no dedicated LSP exists.

This strategy inherits Prolog's grammar substrate (ProbLog files are
syntactically valid SWI-Prolog files augmented with ``::``-prefixed
probabilistic facts) and piggybacks on the same ``swipl`` + ``lsp_server``
pack as the ``PrologStrategy``.

Why only ``quickfix``?
-----------------------
ProbLog's probabilistic semantics make rename and extract operations
research-mode operations:

  - Renaming a probabilistic fact identifier (e.g. ``0.3 :: rain.``) requires
    updating:
      a. The fact name in all call sites.
      b. Any EM-learning weight files (``.pl`` weight files generated by
         ``problog learn``) that reference the fact by name.
      c. Annotation comments and probability tables in documentation.
    The current Prolog LSP backend is unaware of these cross-cutting concerns.

  - Extracting a probabilistic subgoal into a separate predicate changes the
    independence assumptions in the distribution (the extracted predicate
    introduces a new ``grounding`` in the DNF/knowledge compilation step),
    altering the semantics of the model.  This is qualitatively different from
    standard Prolog extraction and cannot be handled safely by a
    syntax-only refactor tool.

``quickfix`` is safe: it covers syntax-level fixes (singleton-variable
warnings, parse errors) that do not affect the probabilistic model.

Mirrors ``Smt2Strategy`` and ``LeanStrategy`` in conservatism level.

ProbLog code action kinds:

  ``quickfix``  — syntax-level diagnostic fixes (singleton variables, parse
                  errors).  Semantics-preserving for the Prolog subset.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .language_strategy import LanguageStrategy
from .lsp_pool import LspPool, LspPoolKey


# Single source of truth for the ProbLog extension allow-list.
_PROBLOG_EXTENSIONS: frozenset[str] = frozenset(
    {
        ".problog",  # canonical ProbLog extension
    }
)

# Code action kinds — conservative by design.
# See module docstring for the probabilistic-semantics rationale.
_PROBLOG_CODE_ACTION_KINDS: frozenset[str] = frozenset(
    {
        # Syntax-level diagnostic fixes only.
        # Rename/extract excluded — see module docstring.
        "quickfix",
    }
)


class ProblogStrategy(LanguageStrategy):
    """Single-LSP ``LanguageStrategy`` for ProbLog (research-mode; swipl backend).

    No dedicated ProbLog LSP exists.  This strategy piggybacks on the
    SWI-Prolog ``lsp_server`` pack, providing syntax-level diagnostics and
    go-to-definition for the pure Prolog subset.  Probabilistic annotations
    are tolerated but not semantics-aware.

    The code-action surface is intentionally minimal (``quickfix`` only).
    See module docstring for the probabilistic-semantics rationale on why
    rename/extract are excluded.

    Install the ProbLog inference engine:
      ``pip install problog``
    Install the LSP backend (shared with Prolog):
      ``swipl -g "pack_install(lsp_server)" -t halt``
    """

    language_id: str = "problog"
    extension_allow_list: frozenset[str] = _PROBLOG_EXTENSIONS
    code_action_allow_list: frozenset[str] = _PROBLOG_CODE_ACTION_KINDS

    def __init__(self, pool: LspPool) -> None:
        self._pool = pool

    def build_servers(self, project_root: Path) -> dict[str, Any]:
        """Return ``{"problog-lsp": <SolidLanguageServer>}`` from the pool.

        Single-LSP language; the dict has exactly one entry.  The pool key
        uses the ``problog`` language id so ProbLog and Prolog workspaces get
        separate pool slots (a single workspace should not mix both).
        """
        key = LspPoolKey(language=self.language_id, project_root=str(project_root))
        server = self._pool.acquire(key)
        return {"problog-lsp": server}

    @classmethod
    def execute_command_whitelist(cls) -> frozenset[str]:
        """Return the set of ``workspace/executeCommand`` verbs this strategy
        will dispatch.

        No ProbLog-specific executeCommand verbs exist.  The whitelist is empty.
        """
        return frozenset()
