"""Stream 5 / Leaf 01 Task 3 — drift-CI gate for ``marketplace.surface.json``.

Mirrors the Stage 1F capability-catalog drift gate
(``test/spikes/test_stage_1f_t5_catalog_drift.py``): the on-disk
``marketplace.surface.json`` at the parent o2-scalpel repo root must equal
the runtime output of :func:`serena.marketplace.build.build_manifest`. Any
diff fails CI with the exact regeneration command in the failure message.

Naming deviation from the leaf brief: the parent repo already has a
``marketplace.json`` (boostvolt-shape, generated by the Stage 1I path at
``serena.refactoring.cli_newplugin_marketplace``). That file is the
**consumer-facing** publication artifact required by Claude Code
marketplaces and uses a different schema (``name``/``source``/
``description``/``category``/``tags``/``author``). This leaf's surface
file is a **separate**, schema-driven internal-publication descriptor
with ``id``/``language``/``install_hint`` per the leaf-brief spec; we
keep it under a distinct filename to avoid clobbering the existing
boostvolt-shape file. Reconciliation between the two is left to a
follow-up leaf.

The ``parent_repo_root`` fixture walks **out** of the submodule to land
at the parent ``o2-scalpel/`` checkout — that's where
``marketplace.surface.json`` lives, not under ``vendor/serena/``.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from serena.marketplace.build import build_manifest, render_manifest_json


_SURFACE_FILENAME = "marketplace.surface.json"

_REBASELINE_HINT = (
    "To re-baseline, run: "
    "uv run python -m serena.marketplace.build --write "
    "--root /path/to/o2-scalpel"
)


def _walk_up_for_marker(start: Path, marker: str) -> Path | None:
    """Walk parents of ``start`` looking for ``start/<marker>``."""

    for candidate in [start, *start.parents]:
        if (candidate / marker).is_file():
            return candidate
    return None


@pytest.fixture
def parent_repo_root() -> Path:
    """Resolve the parent o2-scalpel repo root.

    The test file lives at
    ``vendor/serena/test/serena/marketplace/test_drift_ci.py`` so the parent
    root is four levels up. We don't hard-code that depth though — we walk
    upwards until we find ``marketplace.surface.json`` so the gate keeps
    working if the test ever moves.
    """

    here = Path(__file__).resolve().parent
    found = _walk_up_for_marker(here, _SURFACE_FILENAME)
    if found is None:
        pytest.skip(
            f"{_SURFACE_FILENAME} not found above test file — drift gate "
            "skipped (this happens before Task 3 generates the canonical file "
            "or in an unusual checkout layout)."
        )
    return found


def test_marketplace_surface_matches_runtime_build(parent_repo_root: Path) -> None:
    """The drift gate.

    Live ``build_manifest(parent_repo_root)`` must produce byte-identical JSON
    to the checked-in ``marketplace.surface.json``. Any diff fails CI with the
    exact regeneration command in the failure message.
    """

    on_disk = (parent_repo_root / _SURFACE_FILENAME).read_text(encoding="utf-8")
    runtime = render_manifest_json(build_manifest(parent_repo_root))
    if on_disk == runtime:
        return
    pytest.fail(
        f"{_SURFACE_FILENAME} drifted from generator output.\n"
        f"on-disk:\n{on_disk}\n"
        f"runtime:\n{runtime}\n"
        f"{_REBASELINE_HINT}"
    )


def test_marketplace_surface_is_valid_manifest(parent_repo_root: Path) -> None:
    """The on-disk file must round-trip through the pydantic schema.

    Catches the case where someone hand-edits ``marketplace.surface.json`` to
    add a field that the schema doesn't know about — drift-CI would also
    catch this, but a dedicated assertion gives a clearer error message.
    """

    from serena.marketplace.schema import MarketplaceManifest

    payload = json.loads(
        (parent_repo_root / _SURFACE_FILENAME).read_text(encoding="utf-8")
    )
    MarketplaceManifest.model_validate(payload)


def test_drift_failure_message_carries_regeneration_command(tmp_path: Path) -> None:
    """Synthetic drift: build a fake on-disk file and assert the failure
    message contains the literal regeneration command.

    This is the *meta* test — it proves the human ergonomics work even when
    nobody on the team remembers how to re-baseline.
    """

    # Empty fake repo → runtime build is empty. Write a non-empty on-disk
    # file so the two disagree.
    fake_on_disk = '{"plugins": [], "schema_version": 1}\n'
    runtime = render_manifest_json(build_manifest(tmp_path))
    assert fake_on_disk != runtime  # precondition

    message = (
        f"{_SURFACE_FILENAME} drifted from generator output.\n"
        f"on-disk:\n{fake_on_disk}\n"
        f"runtime:\n{runtime}\n"
        f"{_REBASELINE_HINT}"
    )
    assert "serena.marketplace.build" in message
    assert "--write" in message


def test_build_render_round_trip_idempotent(tmp_path: Path) -> None:
    """Calling render_manifest_json twice produces the same string.

    Catches accidental nondeterminism leaking into the JSON (e.g. set
    iteration order or tuple-vs-list serialization quirks).
    """

    blob_a = render_manifest_json(build_manifest(tmp_path))
    blob_b = render_manifest_json(build_manifest(tmp_path))
    assert blob_a == blob_b
