"""Schema tests for the unified ``marketplace.json`` (v1.2 reconciliation).

The schema absorbed the boostvolt-shape contract that previously lived in
:mod:`serena.refactoring.plugin_schemas`. There is now a single per-plugin
shape (``PluginEntry``) with rich marketplace-UI metadata, and a single
top-level shape (``MarketplaceManifest``) carrying ``$schema`` / ``_generator``
/ ``metadata`` / ``owner`` blocks.
"""

from __future__ import annotations

import pytest
from pydantic import ValidationError

from serena.marketplace.schema import (
    AuthorInfo,
    ManifestMetadata,
    MarketplaceManifest,
    OwnerInfo,
    PluginEntry,
)


def _ok_entry(**overrides: object) -> PluginEntry:
    """Build a minimal valid :class:`PluginEntry`, overriding fields ad hoc."""

    base = {
        "name": "o2-scalpel-rust",
        "version": "1.0.0",
        "source": "./o2-scalpel-rust",
        "description": "Scalpel refactor MCP server for Rust via rust-analyzer",
        "category": "development",
        "tags": ("rust", "rust-analyzer", "lsp", "refactor", "mcp", "scalpel"),
        "author": AuthorInfo(name="AI Hive(R)"),
    }
    base.update(overrides)
    return PluginEntry(**base)  # type: ignore[arg-type]


def _ok_manifest(**overrides: object) -> MarketplaceManifest:
    base = {
        "generator": "Generated by o2-scalpel-newplugin (generator @ deadbeef).",
        "name": "o2-scalpel",
        "metadata": ManifestMetadata(
            description="MCP-driven LSP refactor server for Rust + Python + Markdown.",
            version="1.0.0",
            license="MIT",
            repository="https://github.com/o2services/o2-scalpel",
            homepage="https://github.com/o2services/o2-scalpel",
        ),
        "owner": OwnerInfo(name="AI Hive(R)"),
        "plugins": (_ok_entry(),),
    }
    base.update(overrides)
    return MarketplaceManifest(**base)  # type: ignore[arg-type]


# --- PluginEntry --------------------------------------------------------


def test_plugin_entry_requires_core_boostvolt_fields() -> None:
    e = _ok_entry()
    assert e.name == "o2-scalpel-rust"
    assert e.source == "./o2-scalpel-rust"
    assert e.description.startswith("Scalpel refactor")
    assert e.category == "development"
    assert e.tags[0] == "rust"
    assert e.author.name == "AI Hive(R)"


def test_plugin_entry_rejects_unknown_field() -> None:
    bad_kwargs = {
        "name": "x",
        "version": "1.0.0",
        "source": "./x",
        "description": "x",
        "category": "x",
        "tags": (),
        "author": AuthorInfo(name="x"),
        "unknown_field": "boom",
    }
    with pytest.raises(ValidationError):
        PluginEntry(**bad_kwargs)  # type: ignore[arg-type]


def test_plugin_entry_rejects_bad_semver() -> None:
    with pytest.raises(ValidationError):
        _ok_entry(version="not-a-version")


def test_plugin_entry_is_frozen() -> None:
    e = _ok_entry()
    with pytest.raises(ValidationError):
        e.name = "y"  # type: ignore[misc]


def test_plugin_entry_tags_default_empty() -> None:
    e = _ok_entry(tags=())
    assert e.tags == ()


# --- ManifestMetadata --------------------------------------------------


def test_manifest_metadata_requires_urls() -> None:
    with pytest.raises(ValidationError):
        ManifestMetadata(
            description="x",
            version="1.0.0",
            license="MIT",
            repository="not-a-url",
            homepage="https://example.com",
        )


def test_manifest_metadata_rejects_unknown_field() -> None:
    bad_kwargs = {
        "description": "x",
        "version": "1.0.0",
        "license": "MIT",
        "repository": "https://example.com",
        "homepage": "https://example.com",
        "unknown": "boom",
    }
    with pytest.raises(ValidationError):
        ManifestMetadata(**bad_kwargs)  # type: ignore[arg-type]


# --- MarketplaceManifest -----------------------------------------------


def test_marketplace_manifest_round_trip_via_aliases() -> None:
    m = _ok_manifest()
    payload = m.model_dump(by_alias=True)
    assert payload["$schema"].endswith("marketplace.schema.json")
    assert payload["_generator"].startswith("Generated by o2-scalpel-newplugin")
    assert payload["plugins"][0]["name"] == "o2-scalpel-rust"


def test_marketplace_manifest_rejects_unknown_field() -> None:
    bad_kwargs = {
        "generator": "g",
        "name": "n",
        "metadata": ManifestMetadata(
            description="x",
            version="1.0.0",
            license="MIT",
            repository="https://example.com",
            homepage="https://example.com",
        ),
        "owner": OwnerInfo(name="o"),
        "plugins": (),
        "unknown": "boom",
    }
    with pytest.raises(ValidationError):
        MarketplaceManifest(**bad_kwargs)  # type: ignore[arg-type]


def test_marketplace_manifest_default_schema_url_is_anthropic() -> None:
    m = _ok_manifest()
    assert m.schema_url.endswith("marketplace.schema.json")


def test_author_info_validates_url() -> None:
    with pytest.raises(ValidationError):
        AuthorInfo(name="x", url="not-a-url")


def test_owner_info_validates_url() -> None:
    with pytest.raises(ValidationError):
        OwnerInfo(name="x", url="not-a-url")
