"""Walk a parent repo root and emit the unified ``marketplace.json``.

v1.2 reconciliation: this builder is the **single source of truth** for the
parent-root ``marketplace.json``. It absorbs the role previously split
between :mod:`serena.refactoring.cli_newplugin_marketplace` (boostvolt-shape
``marketplace.json``) and the schema-driven ``marketplace.surface.json`` —
both are gone; a single :func:`build_manifest` populates everything from the
per-plugin ``plugin.json`` files (which now carry ``category`` + ``tags``).

The published o2-scalpel layout has language plugins as direct children of
the parent repo root (``o2-scalpel-rust/``, ``o2-scalpel-python/``,
``o2-scalpel-markdown/``) rather than nested under a ``plugins/`` directory.
The walker therefore globs for ``o2-scalpel-*/.claude-plugin/plugin.json``
from the repo root.

The on-disk file is sorted by plugin name so iteration order is irrelevant —
the drift-CI gate compares byte-for-byte against runtime output and depends
on this determinism.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from serena.marketplace.schema import (
    AuthorInfo,
    ManifestMetadata,
    MarketplaceManifest,
    OwnerInfo,
    PluginEntry,
)

# Top-level marketplace identity. Mirrors the constants used by the per-plugin
# generator (``serena.refactoring.plugin_generator._AUTHOR`` etc) — kept here
# rather than imported across the layering boundary so this module stays a
# strict-leaf publication surface.
_MARKETPLACE_NAME = "o2-scalpel"
_AUTHOR = "AI Hive(R)"
_LICENSE = "MIT"
_REPO = "https://github.com/o2services/o2-scalpel"
_VERSION = "1.0.0"
_DESCRIPTION = "MCP-driven LSP refactor server for Rust + Python + Markdown."

# The ``_generator`` banner is rebuilt at write-time using the submodule's
# current commit SHA so each regeneration carries a fresh provenance stamp.
# When the SHA cannot be resolved (e.g. the engine is installed from a tarball
# rather than a git checkout) we fall back to the literal placeholder used
# elsewhere in the repo (``unknown``).
_GENERATOR_TEMPLATE = (
    "Generated by o2-scalpel-newplugin - do NOT hand-edit. "
    "Regenerate via 'make generate-plugins' (generator @ {sha})."
)
_PLUGIN_DIR_PREFIX = "o2-scalpel-"


def _generator_banner(sha: str) -> str:
    """Render the standard ``_generator`` banner with the supplied SHA."""

    return _GENERATOR_TEMPLATE.format(sha=sha[:12])


def _read_plugin_json(plugin_dir: Path) -> dict:
    """Read ``<plugin_dir>/.claude-plugin/plugin.json`` as a dict."""

    path = plugin_dir / ".claude-plugin" / "plugin.json"
    return json.loads(path.read_text(encoding="utf-8"))


def _author_from(payload: dict) -> AuthorInfo:
    """Build an :class:`AuthorInfo` from a ``plugin.json`` ``author`` block."""

    raw = payload.get("author") or {}
    if isinstance(raw, str):
        return AuthorInfo(name=raw)
    return AuthorInfo(
        name=str(raw.get("name") or _AUTHOR),
        email=raw.get("email"),
        url=raw.get("url"),
    )


def _entry_for(plugin_dir: Path) -> PluginEntry:
    """Build one :class:`PluginEntry` from a plugin tree."""

    data = _read_plugin_json(plugin_dir)
    tags_raw = data.get("tags") or ()
    if not isinstance(tags_raw, (list, tuple)):
        tags_raw = ()
    return PluginEntry(
        name=data["name"],
        version=data["version"],
        source=f"./{plugin_dir.name}",
        description=data["description"],
        category=data.get("category") or "development",
        tags=tuple(tags_raw),
        author=_author_from(data),
    )


def build_manifest(repo_root: Path, *, generator_sha: str = "unknown") -> MarketplaceManifest:
    """Walk ``repo_root`` for ``o2-scalpel-*`` plugin trees.

    :param repo_root: parent o2-scalpel repository root containing one or more
        ``o2-scalpel-<language>/`` plugin trees with ``.claude-plugin/plugin.json``.
    :param generator_sha: provenance stamp baked into the ``_generator`` banner.
        Callers that want a real SHA should resolve ``vendor/serena``'s
        ``HEAD`` and pass it in; the default is ``unknown`` so unit tests
        can exercise the builder without a git environment.
    :return: a frozen :class:`MarketplaceManifest`. Entries are sorted by
        ``name`` so the generator output is byte-identical regardless of
        filesystem iteration order — the drift-CI gate depends on this
        determinism.
    """

    entries: list[PluginEntry] = []
    if repo_root.is_dir():
        for sub in sorted(repo_root.iterdir(), key=lambda p: p.name):
            if not sub.is_dir() or not sub.name.startswith(_PLUGIN_DIR_PREFIX):
                continue
            if not (sub / ".claude-plugin" / "plugin.json").is_file():
                continue
            entries.append(_entry_for(sub))
    # pydantic v2 generates ``__init__`` keyword names from each field's alias
    # when one is defined. ``MarketplaceManifest.generator`` is aliased to
    # ``_generator`` (so the JSON dump preserves the underscore that flags the
    # field as generator-only metadata), so we pass it via the alias-name
    # kwarg dict — pyright reads the same field name and is satisfied.
    return MarketplaceManifest(
        **{"_generator": _generator_banner(generator_sha)},
        name=_MARKETPLACE_NAME,
        metadata=ManifestMetadata(
            description=_DESCRIPTION,
            version=_VERSION,
            license=_LICENSE,
            repository=_REPO,
            homepage=_REPO,
        ),
        owner=OwnerInfo(name=_AUTHOR),
        plugins=tuple(sorted(entries, key=lambda e: e.name)),
    )


def render_manifest_json(manifest: MarketplaceManifest) -> str:
    """Render a :class:`MarketplaceManifest` to canonical JSON.

    The ``sort_keys=True`` + ``indent=2`` + trailing newline format matches
    the convention used elsewhere in the engine (capability catalog, plugin
    generator), giving the drift-CI gate a byte-identical comparison target.
    Aliases (``$schema``, ``_generator``) are honoured so they round-trip
    intact through the dump.
    """

    payload = manifest.model_dump(mode="json", by_alias=True)
    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


MANIFEST_FILENAME = "marketplace.json"
"""On-disk filename for the unified marketplace manifest.

v1.2 collapsed the previous ``marketplace.surface.json`` (schema-driven) and
``marketplace.json`` (boostvolt-shape) into this single file. The rich
boostvolt fields are populated from per-plugin ``plugin.json`` files so the
marketplace builder remains a thin aggregator.
"""


def write_manifest(repo_root: Path, manifest: MarketplaceManifest) -> Path:
    """Write ``manifest`` to ``<repo_root>/marketplace.json``.

    Returns the path written. The same code path is used by the drift-CI
    re-baseline command (``--write``) and by the ``cli_newplugin`` integration
    that updates the marketplace after each plugin emit.
    """

    payload = render_manifest_json(manifest)
    out = repo_root / MANIFEST_FILENAME
    out.write_text(payload, encoding="utf-8")
    return out


def _resolve_engine_sha() -> str:
    """Resolve the engine submodule's HEAD SHA, with a safe fallback.

    The submodule lives at ``vendor/serena`` from the parent root; this
    module sits inside that submodule, so we walk up to find a ``.git``
    directory and read its ``HEAD`` ref. Anything we can't parse falls
    back to ``unknown`` — the banner keeps regenerating with the same
    sentinel until a real SHA is wired in by the caller.
    """

    here = Path(__file__).resolve()
    for parent in here.parents:
        head = parent / ".git" / "HEAD"
        if head.is_file():
            try:
                ref = head.read_text(encoding="utf-8").strip()
            except OSError:
                return "unknown"
            if ref.startswith("ref: "):
                ref_path = parent / ".git" / ref[len("ref: "):]
                if ref_path.is_file():
                    try:
                        return ref_path.read_text(encoding="utf-8").strip() or "unknown"
                    except OSError:
                        return "unknown"
                return "unknown"
            return ref or "unknown"
    return "unknown"


def main(argv: list[str] | None = None) -> int:
    """``python -m serena.marketplace.build`` entry point.

    Without ``--write`` the rendered JSON goes to stdout; with ``--write`` it
    is persisted to ``<root>/marketplace.json``. The drift-CI gate uses the
    no-flag form to compare against the on-disk golden.
    """

    parser = argparse.ArgumentParser(
        prog="serena.marketplace.build",
        description=(
            "Build the unified o2-scalpel marketplace.json from plugin "
            "trees under --root. Replaces the legacy "
            "marketplace.surface.json + cli_newplugin_marketplace pair."
        ),
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path.cwd(),
        help="Parent repo root to scan (default: cwd).",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help=f"Persist the manifest to <root>/{MANIFEST_FILENAME}.",
    )
    parser.add_argument(
        "--generator-sha",
        default=None,
        help=(
            "Override the SHA baked into the _generator banner. Defaults "
            "to the engine submodule's HEAD; passes through to the "
            "drift-CI gate when supplied explicitly."
        ),
    )
    args = parser.parse_args(argv)
    sha = args.generator_sha if args.generator_sha is not None else _resolve_engine_sha()
    manifest = build_manifest(args.root, generator_sha=sha)
    if args.write:
        write_manifest(args.root, manifest)
    else:
        sys.stdout.write(render_manifest_json(manifest))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())


__all__ = [
    "MANIFEST_FILENAME",
    "build_manifest",
    "main",
    "render_manifest_json",
    "write_manifest",
]
