"""
B7 — Generator drift snapshot for canonical rust plugin.

regression: docs/superpowers/specs/2026-05-03-test-coverage-strategy-design.md §6 Phase B B7

Compensating control for the Phase B exclude-22-of-23-plugin-trees decision:
regenerate the canonical rust plugin and diff against the committed tree. Drift
fails the test.

Normalization applied
---------------------
README.md contains a two-line HTML comment banner that embeds the current
submodule HEAD SHA at generation time:

    <!-- Generated by o2-scalpel-newplugin - do NOT hand-edit. -->
    <!-- Regenerate via 'make generate-plugins' (generator @ <SHA12>). -->

The SHA changes with every submodule commit, so the committed canonical README
will always embed the SHA at which it was *last regenerated*, while the test
regenerates against the *current* HEAD. The test strips that banner line before
comparing so the assertion targets content stability, not the ephemeral provenance
stamp. The banner line in plugin.json and .mcp.json was removed from the
generator in v2.0 — this was Category B drift (canonical had stale _generator
field) that was resolved by regenerating the canonical tree in PB15.
"""

from __future__ import annotations

import filecmp
import re
import subprocess
import tempfile
from pathlib import Path

import pytest


# Path from test file: test/unit/ -> test/ -> vendor/serena/ -> vendor/ -> o2-scalpel/ -> o2-scalpel-rust/
# parents[0]=test/unit, [1]=test, [2]=vendor/serena, [3]=vendor, [4]=o2-scalpel (parent repo root)
CANONICAL_TREE = Path(__file__).resolve().parents[4] / "o2-scalpel-rust"

# Pattern matching the README provenance banner line that embeds the submodule SHA.
# The SHA is the only part that legitimately differs between two regenerations at
# different HEAD commits. Strip it before byte-comparison.
_SHA_BANNER_RE = re.compile(
    r"<!-- Regenerate via 'make generate-plugins' \(generator @ [0-9a-f]{12}\)\. -->"
)
_SHA_BANNER_REPLACEMENT = (
    "<!-- Regenerate via 'make generate-plugins' (generator @ <SHA>). -->"
)

# Files whose content must be normalized before comparison.
_NORMALIZE_FILES = frozenset({"README.md"})


@pytest.mark.skipif(
    not CANONICAL_TREE.exists(),
    reason=f"Canonical rust plugin tree not present at {CANONICAL_TREE}",
)
def test_generator_canonical_rust_matches_committed_tree() -> None:
    """Regenerate o2-scalpel-rust and assert zero drift against the committed tree.

    Runs the o2-scalpel-newplugin CLI in a temp directory, then walks both
    trees with filecmp, normalizing the README SHA banner before comparison.
    Any extra, missing, or content-differing file fails the test.
    """
    with tempfile.TemporaryDirectory(prefix="o2-scalpel-newplugin-rust-") as td:
        regen_dir = Path(td)
        result = subprocess.run(
            [
                "uv",
                "run",
                "--project",
                "vendor/serena",
                "o2-scalpel-newplugin",
                "--language",
                "rust",
                "--out",
                str(regen_dir),
            ],
            cwd=str(CANONICAL_TREE.parent),
            capture_output=True,
            text=True,
            timeout=120,
        )
        assert result.returncode == 0, (
            f"o2-scalpel-newplugin failed:\n"
            f"  stdout={result.stdout}\n"
            f"  stderr={result.stderr}"
        )

        # CLI writes to <out>/o2-scalpel-rust/
        regenerated_root = regen_dir / "o2-scalpel-rust"
        assert regenerated_root.exists(), (
            f"Expected generator to create {regenerated_root}; "
            f"contents of {regen_dir}: {list(regen_dir.iterdir())}"
        )

        diffs = _diff_dirs(regenerated_root, CANONICAL_TREE)
        assert not diffs, (
            "Generator drift detected — regenerate canonical tree with "
            "'make generate-plugins' and commit:\n"
            + "\n".join(f"  - {d}" for d in diffs[:50])
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _normalize(rel_path: str, text: str) -> str:
    """Apply content normalization for files with known non-determinism."""
    filename = Path(rel_path).name
    if filename in _NORMALIZE_FILES:
        text = _SHA_BANNER_RE.sub(_SHA_BANNER_REPLACEMENT, text)
    return text


def _files_equal(left: Path, right: Path, rel_path: str) -> bool:
    """Return True if the two files have equal (normalized) content."""
    if rel_path in _NORMALIZE_FILES or Path(rel_path).name in _NORMALIZE_FILES:
        try:
            left_text = _normalize(rel_path, left.read_text(encoding="utf-8"))
            right_text = _normalize(rel_path, right.read_text(encoding="utf-8"))
            return left_text == right_text
        except UnicodeDecodeError:
            pass  # fall through to binary comparison
    return left.read_bytes() == right.read_bytes()


def _diff_dirs(regen: Path, canonical: Path) -> list[str]:
    """Return a list of drift descriptions between *regen* and *canonical*.

    Each entry is a human-readable string describing the nature of the drift
    (file only in regenerated, only in committed, or content differs).
    """
    diffs: list[str] = []

    def walk(left: Path, right: Path, rel_prefix: str = "") -> None:
        cmp = filecmp.dircmp(str(left), str(right))
        for name in cmp.left_only:
            diffs.append(f"{rel_prefix}{name} — only in regenerated")
        for name in cmp.right_only:
            diffs.append(f"{rel_prefix}{name} — only in committed")
        for name in cmp.diff_files:
            rel = rel_prefix + name
            if not _files_equal(left / name, right / name, rel):
                diffs.append(f"{rel} — content differs")
        for sub_name in cmp.subdirs:
            walk(left / sub_name, right / sub_name, rel_prefix + sub_name + "/")

    walk(regen, canonical)
    return diffs
